/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.Category;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author pdavila
 */
public class View extends javax.swing.JFrame {

    private Category getjComboBoxProductCategory;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelContent = new javax.swing.JTabbedPane();
        jPanelClient = new javax.swing.JPanel();
        jScrollPanelClient = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        jPanelClientButtons = new javax.swing.JPanel();
        jButtonClientCreate = new javax.swing.JButton();
        jButtonClientModify = new javax.swing.JButton();
        jButtonClientDelete = new javax.swing.JButton();
        jButtonClientClear = new javax.swing.JButton();
        jLabelClientId = new javax.swing.JLabel();
        jLabelClientOfficialId = new javax.swing.JLabel();
        jLabelClientFullName = new javax.swing.JLabel();
        jLabelClientEmail = new javax.swing.JLabel();
        jLabelClientAddress = new javax.swing.JLabel();
        jLabelClientTelephoneNumber = new javax.swing.JLabel();
        jTextFieldClientId = new javax.swing.JTextField();
        jTextFieldClientOfficialId = new javax.swing.JTextField();
        jTextFieldClientFullName = new javax.swing.JTextField();
        jTextFieldClientEmail = new javax.swing.JTextField();
        jTextFieldClientAddress = new javax.swing.JTextField();
        jTextFieldClientTelephoneNumber = new javax.swing.JTextField();
        jPanelProduct = new javax.swing.JPanel();
        jScrollPanelProduct = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jLabelProductId = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelProductTraceMark = new javax.swing.JLabel();
        jLabelProductModel = new javax.swing.JLabel();
        jLabelProductPrice = new javax.swing.JLabel();
        jTextFieldProductId = new javax.swing.JTextField();
        jTextFieldProductName = new javax.swing.JTextField();
        jTextFieldProductTraceMark = new javax.swing.JTextField();
        jTextFieldProductModel = new javax.swing.JTextField();
        jTextFieldProductPrice = new javax.swing.JTextField();
        jLabelProductStock = new javax.swing.JLabel();
        jComboBoxProductStock = new javax.swing.JComboBox<>();
        jLabelProductCategory = new javax.swing.JLabel();
        jComboBoxProductCategory = new javax.swing.JComboBox<>();
        jLabelProductClient = new javax.swing.JLabel();
        jComboBoxProductClient = new javax.swing.JComboBox<>();
        jPanelProductButtons = new javax.swing.JPanel();
        jButtonProductCreate = new javax.swing.JButton();
        jButtonProductModify = new javax.swing.JButton();
        jButtonProductDelete = new javax.swing.JButton();
        jButtonProductClear = new javax.swing.JButton();
        jPanelStock = new javax.swing.JPanel();
        jScrollPanelStock = new javax.swing.JScrollPane();
        jTableStock = new javax.swing.JTable();
        jLabelStockId = new javax.swing.JLabel();
        jLabelStockTotal = new javax.swing.JLabel();
        jTextFieldStockId = new javax.swing.JTextField();
        jTextFieldStockTotal = new javax.swing.JTextField();
        jPanelStockButtons = new javax.swing.JPanel();
        jButtonStockCreate = new javax.swing.JButton();
        jButtonStockModify = new javax.swing.JButton();
        jButtonStockDelete = new javax.swing.JButton();
        jButtonStockClear = new javax.swing.JButton();
        jPanelCategory = new javax.swing.JPanel();
        jScrollPanelCategory = new javax.swing.JScrollPane();
        jTableCategory = new javax.swing.JTable();
        jLabelCategoryId = new javax.swing.JLabel();
        jLabelCategoryName = new javax.swing.JLabel();
        jLabelCategoryProducts = new javax.swing.JLabel();
        jTextFieldCategoryId = new javax.swing.JTextField();
        jTextFieldCategoryName = new javax.swing.JTextField();
        jScrollPaneCategoryProducts = new javax.swing.JScrollPane();
        jListCategoryProducts = new javax.swing.JList<>();
        jPanelCategoryButtons = new javax.swing.JPanel();
        jButtonCategoryCreate = new javax.swing.JButton();
        jButtonCategoryModify = new javax.swing.JButton();
        jButtonCategoryDelete = new javax.swing.JButton();
        jButtonCategoryClear = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelClient.setViewportView(jTableClient);

        jButtonClientCreate.setText("Crear");

        jButtonClientModify.setText("Modificar");

        jButtonClientDelete.setText("Eliminar");

        jButtonClientClear.setText("Limpiar");

        javax.swing.GroupLayout jPanelClientButtonsLayout = new javax.swing.GroupLayout(jPanelClientButtons);
        jPanelClientButtons.setLayout(jPanelClientButtonsLayout);
        jPanelClientButtonsLayout.setHorizontalGroup(
            jPanelClientButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClientClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClientCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClientModify, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jButtonClientDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelClientButtonsLayout.setVerticalGroup(
            jPanelClientButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonClientCreate)
                .addGap(18, 18, 18)
                .addComponent(jButtonClientModify)
                .addGap(18, 18, 18)
                .addComponent(jButtonClientDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonClientClear)
                .addContainerGap())
        );

        jLabelClientId.setText("Identificador");

        jLabelClientOfficialId.setText("DNI/NIE");

        jLabelClientFullName.setText("Nombre");

        jLabelClientEmail.setText("Email");

        jLabelClientAddress.setText("Dirección");

        jLabelClientTelephoneNumber.setText("Telefono");

        jTextFieldClientId.setEnabled(false);

        javax.swing.GroupLayout jPanelClientLayout = new javax.swing.GroupLayout(jPanelClient);
        jPanelClient.setLayout(jPanelClientLayout);
        jPanelClientLayout.setHorizontalGroup(
            jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPanelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelClientLayout.createSequentialGroup()
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientEmail)
                            .addComponent(jLabelClientId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientOfficialId)
                            .addComponent(jLabelClientAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldClientOfficialId, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldClientAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClientTelephoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClientFullName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldClientTelephoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldClientFullName))))
                .addGap(18, 18, 18)
                .addComponent(jPanelClientButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelClientLayout.setVerticalGroup(
            jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientLayout.createSequentialGroup()
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelClientButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPanelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientId)
                    .addComponent(jTextFieldClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClientOfficialId)
                    .addComponent(jLabelClientFullName)
                    .addComponent(jTextFieldClientOfficialId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldClientFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientEmail)
                    .addComponent(jTextFieldClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClientAddress)
                    .addComponent(jTextFieldClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClientTelephoneNumber)
                    .addComponent(jTextFieldClientTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPanelContent.addTab("Clientes", jPanelClient);

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelProduct.setViewportView(jTableProduct);

        jLabelProductId.setText("Identificador");

        jLabelProductName.setText("Nombre");

        jLabelProductTraceMark.setText("Marca");

        jLabelProductModel.setText("Modelo");

        jLabelProductPrice.setText("Precio");

        jTextFieldProductId.setEnabled(false);

        jLabelProductStock.setText("Stock");

        jLabelProductCategory.setText("Categoria");

        jLabelProductClient.setText("Cliente");

        jButtonProductCreate.setText("Crear");

        jButtonProductModify.setText("Modificar");

        jButtonProductDelete.setText("Eliminar");

        jButtonProductClear.setText("Limpiar");

        javax.swing.GroupLayout jPanelProductButtonsLayout = new javax.swing.GroupLayout(jPanelProductButtons);
        jPanelProductButtons.setLayout(jPanelProductButtonsLayout);
        jPanelProductButtonsLayout.setHorizontalGroup(
            jPanelProductButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProductClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProductModify, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jButtonProductDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProductCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelProductButtonsLayout.setVerticalGroup(
            jPanelProductButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonProductCreate)
                .addGap(18, 18, 18)
                .addComponent(jButtonProductModify)
                .addGap(18, 18, 18)
                .addComponent(jButtonProductDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonProductClear)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelProductLayout = new javax.swing.GroupLayout(jPanelProduct);
        jPanelProduct.setLayout(jPanelProductLayout);
        jPanelProductLayout.setHorizontalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelProductLayout.createSequentialGroup()
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProductId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelProductTraceMark, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelProductPrice, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProductTraceMark, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelProductName)
                            .addComponent(jLabelProductModel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProductStock)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelProductClient)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxProductClient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addComponent(jTextFieldProductModel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProductCategory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jPanelProductButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelProductLayout.setVerticalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductLayout.createSequentialGroup()
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProductButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductLayout.createSequentialGroup()
                        .addComponent(jScrollPanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProductStock)
                            .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProductName)
                            .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProductId))))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelProductCategory)
                        .addComponent(jTextFieldProductModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelProductModel)
                        .addComponent(jTextFieldProductTraceMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelProductTraceMark)))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProductClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProductClient)
                    .addComponent(jTextFieldProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProductPrice))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPanelContent.addTab("Productos", jPanelProduct);

        jTableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelStock.setViewportView(jTableStock);

        jLabelStockId.setText("Identificador");

        jLabelStockTotal.setText("Total");

        jTextFieldStockId.setEnabled(false);

        jButtonStockCreate.setText("Crear");

        jButtonStockModify.setText("Modificar");

        jButtonStockDelete.setText("Eliminar");

        jButtonStockClear.setText("Limpiar");

        javax.swing.GroupLayout jPanelStockButtonsLayout = new javax.swing.GroupLayout(jPanelStockButtons);
        jPanelStockButtons.setLayout(jPanelStockButtonsLayout);
        jPanelStockButtonsLayout.setHorizontalGroup(
            jPanelStockButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStockButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelStockButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonStockClear, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addGroup(jPanelStockButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonStockDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonStockModify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(jButtonStockCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelStockButtonsLayout.setVerticalGroup(
            jPanelStockButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStockCreate)
                .addGap(18, 18, 18)
                .addComponent(jButtonStockModify)
                .addGap(18, 18, 18)
                .addComponent(jButtonStockDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonStockClear)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelStockLayout = new javax.swing.GroupLayout(jPanelStock);
        jPanelStock.setLayout(jPanelStockLayout);
        jPanelStockLayout.setHorizontalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStockLayout.createSequentialGroup()
                        .addComponent(jScrollPanelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelStockButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelStockLayout.createSequentialGroup()
                        .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelStockTotal)
                            .addComponent(jLabelStockId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldStockId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStockTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStockLayout.setVerticalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelStockButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPanelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStockId)
                    .addComponent(jTextFieldStockId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStockTotal)
                    .addComponent(jTextFieldStockTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jTabbedPanelContent.addTab("Stock", jPanelStock);

        jTableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelCategory.setViewportView(jTableCategory);

        jLabelCategoryId.setText("Identificador");

        jLabelCategoryName.setText("Nombre");

        jLabelCategoryProducts.setText("Productos");

        jTextFieldCategoryId.setEnabled(false);

        jScrollPaneCategoryProducts.setViewportView(jListCategoryProducts);

        jButtonCategoryCreate.setText("Crear");

        jButtonCategoryModify.setText("Modificar");

        jButtonCategoryDelete.setText("Eliminar");

        jButtonCategoryClear.setText("Limpiar");

        javax.swing.GroupLayout jPanelCategoryButtonsLayout = new javax.swing.GroupLayout(jPanelCategoryButtons);
        jPanelCategoryButtons.setLayout(jPanelCategoryButtonsLayout);
        jPanelCategoryButtonsLayout.setHorizontalGroup(
            jPanelCategoryButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCategoryButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonCategoryModify, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jButtonCategoryDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCategoryClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCategoryCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelCategoryButtonsLayout.setVerticalGroup(
            jPanelCategoryButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCategoryCreate)
                .addGap(18, 18, 18)
                .addComponent(jButtonCategoryModify)
                .addGap(18, 18, 18)
                .addComponent(jButtonCategoryDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonCategoryClear)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelCategoryLayout = new javax.swing.GroupLayout(jPanelCategory);
        jPanelCategory.setLayout(jPanelCategoryLayout);
        jPanelCategoryLayout.setHorizontalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addComponent(jScrollPanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCategoryButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCategoryName)
                            .addComponent(jLabelCategoryId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                                .addComponent(jTextFieldCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                .addComponent(jLabelCategoryProducts)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneCategoryProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCategoryLayout.setVerticalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCategoryButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCategoryId)
                            .addComponent(jTextFieldCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCategoryProducts))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCategoryName)
                            .addComponent(jTextFieldCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneCategoryProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTabbedPanelContent.addTab("Categoria", jPanelCategory);

        jLabelTitle.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelTitle.setText("VENTAS");

        jButtonExit.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPanelContent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabelTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(460, 460, 460))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    
    /**
     * General
     */
    public JLabel getjLabelTitle() { return jLabelTitle; }
    public JTabbedPane getjTabbedPanelContent() { return jTabbedPanelContent; }
    public JButton getjButtonExit() { return jButtonExit; }
    
    
    /**
     * Products
     */
    public JButton getjButtonProductCreate() { return jButtonProductCreate; }
    public JButton getjButtonProductModify() { return jButtonProductModify; }
    public JButton getjButtonProductDelete() { return jButtonProductDelete; }
    public JButton getjButtonProductClear() { return jButtonProductClear; }
    
    public JLabel getjLabelProductId() { return jLabelProductId; }
    public JLabel getjLabelProductName() { return jLabelProductName; }
    public JLabel getjLabelProductTraceMark() { return jLabelProductTraceMark; }
    public JLabel getjLabelProductModel() { return jLabelProductModel; }
    public JLabel getjLabelProductPrice() { return jLabelProductPrice; }
    public JLabel getjLabelProductStock() { return jLabelProductStock; }
    public JLabel getjLabelProductCategory() { return jLabelProductCategory; }
    
    public JComboBox<String> getjComboBoxProductStock() { return jComboBoxProductStock; }
    public JComboBox<String> getjComboBoxProductCategory() { return jComboBoxProductCategory; }
    public JComboBox<String> getjComboBoxProductClient() { return jComboBoxProductClient; }
     
    public JPanel getjPanelProduct() { return jPanelProduct; }
    public JPanel getjPanelProductButtons() { return jPanelProductButtons; }
    
    public JScrollPane getjScrollPanelProduct() { return jScrollPanelProduct; }
    
    public JTable getjTableProduct() { return jTableProduct; }
    
    public JTextField getjTextFieldProductId() { return jTextFieldProductId; }
    public JTextField getjTextFieldProductName() { return jTextFieldProductName; }
    public JTextField getjTextFieldProductTraceMark() { return jTextFieldProductTraceMark; }
    public JTextField getjTextFieldProductModel() { return jTextFieldProductModel; }    
    public JTextField getjTextFieldProductPrice() { return jTextFieldProductPrice; }

    
    /**
     * Stock
     */
    public JButton getjButtonStockCreate() { return jButtonStockCreate; }
    public JButton getjButtonStockModify() { return jButtonStockModify; }
    public JButton getjButtonStockDelete() { return jButtonStockDelete; }
    public JButton getjButtonStockClear() { return jButtonStockClear; }
    
    public JLabel getjLabelStockId() { return jLabelStockId; }
    public JLabel getjLabelStockTotal() { return jLabelStockTotal; }
    
    public JPanel getjPanelStock() { return jPanelStock; }
    public JPanel getjPanelStockButtons() { return jPanelStockButtons; }
    
    public JScrollPane getjScrollPanelStock() { return jScrollPanelStock; }
    
    public JTable getjTableStock() { return jTableStock; }
    
    public JTextField getjTextFieldStockId() { return jTextFieldStockId; }
    public JTextField getjTextFieldStockTotal() { return jTextFieldStockTotal; }
    
    
    /**
     * Category
     */
    public JButton getjButtonCategoryCreate() { return jButtonCategoryCreate; }
    public JButton getjButtonCategoryModify() { return jButtonCategoryModify; }
    public JButton getjButtonCategoryDelete() { return jButtonCategoryDelete; }
    public JButton getjButtonCategoryClear() { return jButtonCategoryClear; }

    public JLabel getjLabelCategoryId() { return jLabelCategoryId; }
    public JLabel getjLabelCategoryName() { return jLabelCategoryName; }

    public JPanel getjPanelCategory() { return jPanelCategory; }
    public JPanel getjPanelCategoryButtons() { return jPanelCategoryButtons; }

    public JScrollPane getjScrollPanelCategory() { return jScrollPanelCategory; }

    public JTable getjTableCategory() { return jTableCategory; }

    public JTextField getjTextFieldCategoryId() { return jTextFieldCategoryId; }
    public JTextField getjTextFieldCategoryName() { return jTextFieldCategoryName; }
    
    
    /**
     * Client
     */    
    public JButton getjButtonClientCreate() { return jButtonClientCreate; }
    public JButton getjButtonClientModify() { return jButtonClientModify; }
    public JButton getjButtonClientDelete() { return jButtonClientDelete; }
    public JButton getjButtonClientClear() { return jButtonClientClear; }
    
    public JLabel getjLabelClientId() { return jLabelClientId; }
    public JLabel getjLabelClientOfficialId() { return jLabelClientOfficialId; }
    public JLabel getjLabelClientFullName() { return jLabelClientFullName; }
    public JLabel getjLabelClientEmail() { return jLabelClientEmail; }
    public JLabel getjLabelClientAddress() { return jLabelClientAddress; }
    public JLabel getjLabelClientTelephoneNumber() { return jLabelClientTelephoneNumber; }
    
    public JPanel getjPanelClient() { return jPanelClient; }
    public JPanel getjPanelClientButtons() { return jPanelClientButtons; }

    public JScrollPane getjScrollPanelClient() { return jScrollPanelClient; }

    public JTable getjTableClient() { return jTableClient; }

    public JTextField getjTextFieldClientId() { return jTextFieldClientId; }
    public JTextField getjTextFieldClientOfficialId() { return jTextFieldClientOfficialId; }
    public JTextField getjTextFieldClientFullName() { return jTextFieldClientFullName; }
    public JTextField getjTextFieldClientEmail() { return jTextFieldClientEmail; }
    public JTextField getjTextFieldClientAddress() { return jTextFieldClientAddress; }
    public JTextField getjTextFieldClientTelephoneNumber() { return jTextFieldClientTelephoneNumber; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCategoryClear;
    private javax.swing.JButton jButtonCategoryCreate;
    private javax.swing.JButton jButtonCategoryDelete;
    private javax.swing.JButton jButtonCategoryModify;
    private javax.swing.JButton jButtonClientClear;
    private javax.swing.JButton jButtonClientCreate;
    private javax.swing.JButton jButtonClientDelete;
    private javax.swing.JButton jButtonClientModify;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonProductClear;
    private javax.swing.JButton jButtonProductCreate;
    private javax.swing.JButton jButtonProductDelete;
    private javax.swing.JButton jButtonProductModify;
    private javax.swing.JButton jButtonStockClear;
    private javax.swing.JButton jButtonStockCreate;
    private javax.swing.JButton jButtonStockDelete;
    private javax.swing.JButton jButtonStockModify;
    private javax.swing.JComboBox<String> jComboBoxProductCategory;
    private javax.swing.JComboBox<String> jComboBoxProductClient;
    private javax.swing.JComboBox<String> jComboBoxProductStock;
    private javax.swing.JLabel jLabelCategoryId;
    private javax.swing.JLabel jLabelCategoryName;
    private javax.swing.JLabel jLabelCategoryProducts;
    private javax.swing.JLabel jLabelClientAddress;
    private javax.swing.JLabel jLabelClientEmail;
    private javax.swing.JLabel jLabelClientFullName;
    private javax.swing.JLabel jLabelClientId;
    private javax.swing.JLabel jLabelClientOfficialId;
    private javax.swing.JLabel jLabelClientTelephoneNumber;
    private javax.swing.JLabel jLabelProductCategory;
    private javax.swing.JLabel jLabelProductClient;
    private javax.swing.JLabel jLabelProductId;
    private javax.swing.JLabel jLabelProductModel;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelProductPrice;
    private javax.swing.JLabel jLabelProductStock;
    private javax.swing.JLabel jLabelProductTraceMark;
    private javax.swing.JLabel jLabelStockId;
    private javax.swing.JLabel jLabelStockTotal;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jListCategoryProducts;
    private javax.swing.JPanel jPanelCategory;
    private javax.swing.JPanel jPanelCategoryButtons;
    private javax.swing.JPanel jPanelClient;
    private javax.swing.JPanel jPanelClientButtons;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JPanel jPanelProductButtons;
    private javax.swing.JPanel jPanelStock;
    private javax.swing.JPanel jPanelStockButtons;
    private javax.swing.JScrollPane jScrollPaneCategoryProducts;
    private javax.swing.JScrollPane jScrollPanelCategory;
    private javax.swing.JScrollPane jScrollPanelClient;
    private javax.swing.JScrollPane jScrollPanelProduct;
    private javax.swing.JScrollPane jScrollPanelStock;
    private javax.swing.JTabbedPane jTabbedPanelContent;
    private javax.swing.JTable jTableCategory;
    private javax.swing.JTable jTableClient;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTable jTableStock;
    private javax.swing.JTextField jTextFieldCategoryId;
    private javax.swing.JTextField jTextFieldCategoryName;
    private javax.swing.JTextField jTextFieldClientAddress;
    private javax.swing.JTextField jTextFieldClientEmail;
    private javax.swing.JTextField jTextFieldClientFullName;
    private javax.swing.JTextField jTextFieldClientId;
    private javax.swing.JTextField jTextFieldClientOfficialId;
    private javax.swing.JTextField jTextFieldClientTelephoneNumber;
    private javax.swing.JTextField jTextFieldProductId;
    private javax.swing.JTextField jTextFieldProductModel;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldProductPrice;
    private javax.swing.JTextField jTextFieldProductTraceMark;
    private javax.swing.JTextField jTextFieldStockId;
    private javax.swing.JTextField jTextFieldStockTotal;
    // End of variables declaration//GEN-END:variables

    public Category getGetjComboBoxProductCategory() {
        return getjComboBoxProductCategory;
    }

    public javax.swing.JLabel getjLabelCategoryProducts() {
        return jLabelCategoryProducts;
    }

    public javax.swing.JLabel getjLabelProductClient() {
        return jLabelProductClient;
    }

    public javax.swing.JList<String> getjListCategoryProducts() {
        return jListCategoryProducts;
    }

    public javax.swing.JScrollPane getjScrollPaneCategoryProducts() {
        return jScrollPaneCategoryProducts;
    }

}
